# Generated by Django 5.2 on 2025-05-17 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_profile_clinic_address_profile_clinic_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='預約日期')),
                ('time', models.TimeField(verbose_name='預約時間')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='預約原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='飼主')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet', verbose_name='預約寵物')),
                ('vet', models.ForeignKey(limit_choices_to={'account_type': 'vet'}, on_delete=django.db.models.deletion.CASCADE, to='petapp.profile', verbose_name='預約獸醫')),
            ],
        ),
    ]
