# Generated by Django 5.2 on 2025-08-31 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('is_available', models.BooleanField(default=True, verbose_name='可預約')),
                ('max_bookings', models.IntegerField(default=1, verbose_name='最大預約數')),
                ('current_bookings', models.IntegerField(default=0, verbose_name='目前預約數')),
                ('source', models.CharField(choices=[('schedule', '排班生成'), ('manual', '手動新增'), ('exception', '例外排班')], default='schedule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '預約時段',
                'verbose_name_plural': '預約時段',
            },
        ),
        migrations.CreateModel(
            name='HandoffTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('contact', models.CharField(blank=True, max_length=128)),
                ('channel', models.CharField(default='web', max_length=32)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_open', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='寵物類型名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='寵物代碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '寵物類型',
                'verbose_name_plural': '寵物類型',
                'db_table': 'pet_types',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='服務名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='服務代碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '服務類型',
                'verbose_name_plural': '服務類型',
                'db_table': 'pet_service_types',
            },
        ),
        migrations.CreateModel(
            name='VetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100, verbose_name='診所名稱')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='開業執照字號')),
                ('clinic_phone', models.CharField(max_length=20, verbose_name='診所電話')),
                ('clinic_address', models.CharField(max_length=255, verbose_name='診所地址')),
                ('clinic_email', models.EmailField(max_length=254, verbose_name='診所信箱')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已通過農委會驗證')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='驗證日期')),
                ('moa_county', models.CharField(blank=True, max_length=20, verbose_name='縣市')),
                ('moa_status', models.CharField(blank=True, max_length=20, verbose_name='開業狀態')),
                ('moa_responsible_vet', models.CharField(blank=True, max_length=50, verbose_name='負責獸醫')),
                ('moa_issue_date', models.DateField(blank=True, null=True, verbose_name='發照日期')),
                ('default_appointment_duration', models.IntegerField(default=30, verbose_name='預設預約時長(分鐘)')),
                ('advance_booking_days', models.IntegerField(default=30, verbose_name='可提前預約天數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '獸醫院',
                'verbose_name_plural': '獸醫院',
            },
        ),
        migrations.CreateModel(
            name='HandoffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'user'), ('agent', 'agent'), ('system', 'system')], max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='petapp.handoffticket')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', '狗'), ('cat', '貓'), ('other', '其他')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sterilization_status', models.CharField(choices=[('sterilized', '已絕育'), ('not_sterilized', '未絕育'), ('unknown', '未知')], max_length=20)),
                ('chip', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], max_length=10)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('feature', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pet_pictures/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='飼主')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('diet', '飲食習慣'), ('exercise', '運動習慣'), ('allergen', '過敏源'), ('other', '其他'), ('temperature', '體溫'), ('weight', '體重')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('owner', '飼主'), ('clinic_admin', '診所管理員'), ('veterinarian', '獸醫師')], max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='手機號碼')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DewormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='驅蟲品牌')),
                ('date', models.DateField(verbose_name='施打日期')),
                ('location', models.CharField(max_length=200, verbose_name='施打地點')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deworm_records', to='petapp.pet', verbose_name='寵物')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petapp.profile', verbose_name='施打醫師')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='reports/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='petapp.pet')),
                ('vet', models.ForeignKey(limit_choices_to={'account_type': 'vet'}, on_delete=django.db.models.deletion.CASCADE, to='petapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名稱')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('website', models.TextField(blank=True, null=True, verbose_name='網站')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='地區')),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='緯度')),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='經度')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='評分')),
                ('rating_count', models.IntegerField(blank=True, null=True, verbose_name='評分數量')),
                ('has_emergency', models.BooleanField(default=False, verbose_name='提供24小時急診')),
                ('business_hours', models.JSONField(blank=True, null=True, verbose_name='營業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('pet_types', models.ManyToManyField(blank=True, related_name='locations', to='petapp.pettype', verbose_name='支援寵物類型')),
                ('service_types', models.ManyToManyField(blank=True, related_name='locations', to='petapp.servicetype', verbose_name='服務類型')),
            ],
            options={
                'verbose_name': '寵物地點',
                'verbose_name_plural': '寵物地點',
                'db_table': 'pet_locations',
            },
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='疫苗品牌')),
                ('date', models.DateField(verbose_name='施打日期')),
                ('location', models.CharField(max_length=200, verbose_name='施打地點')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='petapp.pet', verbose_name='寵物')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petapp.profile', verbose_name='施打醫師')),
            ],
        ),
        migrations.CreateModel(
            name='VetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='預約原因')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('completed', '已完成'), ('cancelled', '已取消'), ('no_show', '未到診')], default='confirmed', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='聯絡信箱')),
                ('booking_type', models.CharField(choices=[('online', '線上預約'), ('phone', '電話預約'), ('walkin', '現場預約')], default='online', max_length=20)),
                ('clinic_notified', models.BooleanField(default=False, verbose_name='已通知診所')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='已發送提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='飼主')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet', verbose_name='預約寵物')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.appointmentslot', verbose_name='預約時段')),
            ],
            options={
                'verbose_name': '預約記錄',
                'verbose_name_plural': '預約記錄',
            },
        ),
        migrations.CreateModel(
            name='VetAvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期日')], verbose_name='星期')),
                ('time_slot', models.CharField(choices=[('morning', '早上'), ('afternoon', '下午'), ('evening', '晚上')], max_length=10, verbose_name='時段')),
                ('start_time', models.TimeField(verbose_name='看診開始時間')),
                ('end_time', models.TimeField(verbose_name='看診結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('vet', models.ForeignKey(limit_choices_to={'account_type': 'vet'}, on_delete=django.db.models.deletion.CASCADE, to='petapp.profile', verbose_name='獸醫')),
            ],
            options={
                'verbose_name': '獸醫排班時段',
                'verbose_name_plural': '獸醫排班時段',
            },
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.vetclinic'),
        ),
        migrations.CreateModel(
            name='VetDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_license_number', models.CharField(blank=True, max_length=50, verbose_name='獸醫師執照號碼')),
                ('license_verified_with_moa', models.BooleanField(default=False, verbose_name='農委會執照驗證')),
                ('moa_license_type', models.CharField(blank=True, max_length=20, verbose_name='執照類別')),
                ('moa_clinic_name', models.CharField(blank=True, max_length=100, verbose_name='診所名稱')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='專科領域')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='執業年資')),
                ('bio', models.TextField(blank=True, verbose_name='個人簡介')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='petapp.vetclinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='看診日期')),
                ('clinic_location', models.CharField(max_length=100, verbose_name='看診地點')),
                ('diagnosis', models.TextField(verbose_name='診斷結果')),
                ('treatment', models.TextField(verbose_name='治療內容')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='記錄填寫者')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet', verbose_name='寵物')),
                ('attending_vet', models.ForeignKey(limit_choices_to={'license_verified_with_moa': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_records', to='petapp.vetdoctor', verbose_name='看診獸醫師')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.vetdoctor'),
        ),
        migrations.CreateModel(
            name='VetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '週一'), (1, '週二'), (2, '週三'), (3, '週四'), (4, '週五'), (5, '週六'), (6, '週日')], verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用排班')),
                ('appointment_duration', models.IntegerField(default=30, verbose_name='預約時長(分鐘)')),
                ('max_appointments_per_slot', models.IntegerField(default=1, verbose_name='每時段最大預約數')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='petapp.vetdoctor')),
            ],
            options={
                'verbose_name': '獸醫師排班',
                'verbose_name_plural': '獸醫師排班',
            },
        ),
        migrations.CreateModel(
            name='VetScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('leave', '請假'), ('holiday', '休假'), ('special', '特殊排班'), ('unavailable', '暫停預約')], max_length=20, verbose_name='例外類型')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='結束時間')),
                ('alternative_start_time', models.TimeField(blank=True, null=True, verbose_name='替代開始時間')),
                ('alternative_end_time', models.TimeField(blank=True, null=True, verbose_name='替代結束時間')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='petapp.vetdoctor')),
            ],
            options={
                'verbose_name': '排班例外',
                'verbose_name_plural': '排班例外',
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '週一'), (1, '週二'), (2, '週三'), (3, '週四'), (4, '週五'), (5, '週六'), (6, '週日')], verbose_name='星期')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='開始時間')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='結束時間')),
                ('period_order', models.PositiveIntegerField(default=1, verbose_name='時段順序')),
                ('period_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='時段名稱')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours_detail', to='petapp.petlocation', verbose_name='地點')),
            ],
            options={
                'verbose_name': '營業時間',
                'verbose_name_plural': '營業時間',
                'db_table': 'pet_business_hours',
                'ordering': ['day_of_week', 'period_order'],
                'indexes': [models.Index(fields=['location', 'day_of_week'], name='business_hours_idx')],
                'unique_together': {('location', 'day_of_week', 'period_order')},
            },
        ),
        migrations.AddIndex(
            model_name='petlocation',
            index=models.Index(fields=['city', 'district'], name='city_district_idx'),
        ),
        migrations.AddIndex(
            model_name='petlocation',
            index=models.Index(fields=['has_emergency'], name='emergency_idx'),
        ),
        migrations.AddIndex(
            model_name='petlocation',
            index=models.Index(fields=['lat', 'lon'], name='location_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vetavailabletime',
            unique_together={('vet', 'weekday', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('doctor', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='vetschedule',
            unique_together={('doctor', 'weekday', 'start_time')},
        ),
    ]
