# Generated by Django 5.2 on 2025-04-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('狗', 'Dog'), ('貓', 'Cat'), ('其他', 'Other')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sterilization_status', models.CharField(choices=[('已絕育', 'Yes'), ('未絕育', 'No'), ('未知', 'Unknown')], max_length=10)),
                ('chip', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('公', 'Male'), ('母', 'Female'), ('unknown', '未知')], max_length=10)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('feature', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pet_pictures/')),
            ],
        ),
    ]
