# Generated by Django 5.2 on 2025-04-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', '狗'), ('cat', '貓'), ('other', '其他')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sterilization_status',
            field=models.CharField(choices=[('sterilized', '已絕育'), ('not_sterilized', '未絕育'), ('unknown', '未知')], max_length=20),
        ),
    ]
