# Generated by Django 5.2 on 2025-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified_vet',
            field=models.BooleanField(default=False, verbose_name='獸醫身分已驗證'),
        ),
    ]
