# Generated by Django 5.2 on 2025-04-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_alter_pet_gender_alter_pet_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
