# Generated by Django 5.2 on 2025-04-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_pet_year_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='day_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='month_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
