# Generated by Django 5.2 on 2025-04-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_pet_day_of_birth_pet_month_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='date_of_birth',
        ),
    ]
