# Generated by Django 5.2 on 2025-05-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_profile_vet_license_profile_vet_license_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', '狗'), ('cat', '貓'), ('other', '其他')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sterilization_status', models.CharField(choices=[('sterilized', '已絕育'), ('not_sterilized', '未絕育'), ('unknown', '未知')], max_length=20)),
                ('chip', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('month_of_birth', models.IntegerField(blank=True, null=True)),
                ('day_of_birth', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], max_length=10)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('feature', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pet_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('diet', '飲食習慣'), ('exercise', '運動習慣'), ('allergen', '過敏源'), ('other', '其他'), ('temperature', '體溫'), ('weight', '體重')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet')),
            ],
        ),
    ]
