# Generated by Django 5.2 on 2025-05-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_pet_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='醫院／診所地址'),
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='醫院／診所名稱'),
        ),
    ]
