# Generated by Django 5.2 on 2025-05-22 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='day_of_birth',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='month_of_birth',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DewormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='驅蟲品牌')),
                ('date', models.DateField(verbose_name='施打日期')),
                ('location', models.CharField(max_length=200, verbose_name='施打地點')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deworm_records', to='petapp.pet', verbose_name='寵物')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petapp.profile', verbose_name='施打醫師')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='看診日期')),
                ('clinic_location', models.CharField(max_length=100, verbose_name='看診地點')),
                ('diagnosis', models.TextField(verbose_name='診斷結果')),
                ('treatment', models.TextField(verbose_name='治療內容')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet', verbose_name='寵物')),
                ('vet', models.ForeignKey(limit_choices_to={'account_type': 'vet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petapp.profile', verbose_name='看診獸醫')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='reports/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='petapp.pet')),
                ('vet', models.ForeignKey(limit_choices_to={'account_type': 'vet'}, on_delete=django.db.models.deletion.CASCADE, to='petapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='疫苗品牌')),
                ('date', models.DateField(verbose_name='施打日期')),
                ('location', models.CharField(max_length=200, verbose_name='施打地點')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='petapp.pet', verbose_name='寵物')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petapp.profile', verbose_name='施打醫師')),
            ],
        ),
        migrations.CreateModel(
            name='VetAvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期日')], verbose_name='星期')),
                ('time_slot', models.CharField(choices=[('morning', '早上'), ('afternoon', '下午'), ('evening', '晚上')], max_length=10, verbose_name='時段')),
                ('start_time', models.TimeField(verbose_name='看診開始時間')),
                ('end_time', models.TimeField(verbose_name='看診結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('vet', models.ForeignKey(limit_choices_to={'account_type': 'vet'}, on_delete=django.db.models.deletion.CASCADE, to='petapp.profile', verbose_name='獸醫')),
            ],
            options={
                'verbose_name': '獸醫排班時段',
                'verbose_name_plural': '獸醫排班時段',
                'unique_together': {('vet', 'weekday', 'time_slot')},
            },
        ),
    ]
