# Generated by Django 5.2 on 2025-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_profile_is_verified_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vet_license',
            field=models.FileField(blank=True, null=True, upload_to='vet_licenses/', verbose_name='獸醫證照'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vet_license_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='執業執照縣市'),
        ),
    ]
